sudo: required
dist: trusty
language: node_js
cache:
  directories:
  - node_modules
node_js:
- lts/*
- 8 
###################
only:
- master
before_install:
install:
- npm install
before_script:
script:
- npm run test
- npm run build
after_success:
- chmod +x .travis/push.sh
- .travis/push.sh
after_failure:
- ls -a
